title: My GitHub Page of Remote Theme
description: My personal GitHub Page
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache
